### ISSUE TITLE
V1.0 development Plan

### ISSUE THREAD

**Issue by sullyy9** [sullyy9/martel-integration-testing#1]
### Tasks
- [x] Allow selection of which generated files are saved and where.
- [x] Fix issues with L433 printout generation.
- [x] Add RS232 and IR comms interfaces to printer test library.
- [ ] Better management of device setup in test initialisation.
- [ ] Flesh out test suite.
- [ ] Set up CI pipeline with library testing.
- [ ] Move to a more suitable analyser / test rig.
